version: '3'

services:
  api:
    build: .
    container_name: pebble-crypto-api
    ports:
      - "8000:${PORT:-8000}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./app:/code/app  # For development - enables live code reloading
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload 
